### PR TITLE
Update Instructions

### PR DESCRIPTION
**Pull request by innocentvoice**
Make it easier for people with zero knowledge

### CODE REVIEW

**Comment by h3x4n1um** [comment]
Vietnamese instruction should split into the `README_VN.md` file instead

**Comment by innocentvoice** [comment]
> Vietnamese instruction should split into the `README_VN.md` file instead

it seems @tsuntsun1 didn't do that, i will do it instead

**Comment by innocentvoice** [comment]
Please check

**Comment by h3x4n1um** [comment]
LGTM

**Pull request merged**
